---
- hosts: all
  tasks: 
  - name: Disable password login
    lineinfile: dest={{ sshd_config }} regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
    notify: restart sshd
  handlers:
  - name: restart sshd
    serivce:
      name: sshd
      state: restarted
