---
- hosts: localhost
  remote_user: root
  tasks:
    - name: convert VM
      shell: 'ovftool --noSSLVerify vi://root:"{{ password }}"@192.168.2.5/rhel6test /tmp/migration.ova'
    - name: upload test
      s3:
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        bucket: jr-imageupload
        object: images/testimage.ova
        src: /tmp/migration.ova
        mode: put
