---
- hosts: localhost
  connection: local
  tasks:
    - name: Authenticate to RHV-M
      ovirt_auth:
        url: "https://{{ rhvm_addr }}/ovirt-engine/api"
        username: "{{ rhv_user }}"
        password: "{{ rhv_pass }}"
        insecure: true

    - name: Untag VM as 'provsioning'
      ovirt_tags:
        auth: "{{ ovirt_auth }}"
        name: provisioning
        state: detached
        vms:
          - "{{ vm_name }}"
