---
- hosts: all
  tasks: 
  - name: create user
    user: 
      name: '{{ user }}' 
      state: present
      password: '$6$YPIBMYxCoTfxOl9S$UTt0hh2qWJ9LbwcKWOyyi7mAUaCb9UEIbDouGQNdogNCcudcFWYhDqubqymTUOXZnTITIQ6am15RkUSKfs9bD1'
      uid: '{{ uid }}'
      groups: wheel
      append: yes
  - name: Copy SSH Key
    authorized_key:
      user: '{{ user }}'
      state: present
      key: '{{ key }}'
