---
- hosts: all
  tasks: 
  - name: create user
    user: 
      name: '{{ user }}' 
      state: present
      uid: '{{ uid }}'
      groups: wheel
      append: yes
  - name: Copy SSH Key
    authorized_key:
      user: '{{ user }}'
      state: present
      key: '{{ key_url }}'
