---
#This playbook is intended to join a host to a specific satellite 6 server
- hosts: all
  remote_user: root
  tasks:
    - name: Register to Lab Satellite Server
      redhat_subscription:
        state: present
        activationkey: rhel7base
        org_id: 1
